package enums;

public enum TokenName {
	
	// Todos os possiveis tipos de tokens
	PALAVRA_RESERVADA,
	NOME_VARIAVEL,
	OPERADOR_MATEMATICO, 
	NUMEROS, 
	OPERADOR_COMPARACAO, 
	OPERADOR_ATRIBUICAO,
	FINAL_LINHA,
	SIMBOLO,
	ESPACO,
	NEGACAO,
	TOKEN_MAL_FORMADO
}
